# Generated by Django 6.1.1 on 2026-09-03 17:00

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email_verified', models.BooleanField(default=False, help_text="Whether the user's email has been verified")),
                ('email_verified_at', models.DateTimeField(blank=True, help_text='When the email was verified', null=True)),
                ('email_verification_token', models.CharField(blank=True, help_text='Token for email verification link', max_length=64, null=True)),
                ('email_verification_token_created_at', models.DateTimeField(blank=True, null=True)),
                ('kyc_status', models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_started', help_text='Current KYC verification status', max_length=20)),
                ('kyc_submitted_at', models.DateTimeField(blank=True, help_text='When KYC documents were submitted', null=True)),
                ('kyc_verified_at', models.DateTimeField(blank=True, help_text='When KYC was approved', null=True)),
                ('kyc_rejection_reason', models.TextField(blank=True, help_text='Reason for KYC rejection (if rejected)')),
                ('phone', models.CharField(blank=True, help_text='Phone number (optional)', max_length=20)),
                ('profile_image', models.ImageField(blank=True, help_text="User's profile picture", null=True, upload_to='profile_images/')),
                ('timezone', models.CharField(default='UTC', help_text="User's timezone", max_length=50)),
                ('preferred_currency', models.CharField(default='USD', help_text="User's preferred currency (e.g., USD, EUR, GBP)", max_length=3)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, help_text="Available balance in user's preferred currency", max_digits=20)),
                ('total_invested', models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount currently invested in strategies', max_digits=20)),
                ('total_deposited', models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount deposited (lifetime)', max_digits=20)),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount withdrawn (lifetime)', max_digits=20)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, help_text='IP address of last login', null=True)),
                ('failed_login_attempts', models.IntegerField(default=0, help_text='Number of consecutive failed login attempts')),
                ('account_locked_until', models.DateTimeField(blank=True, help_text='Account is locked until this time (after too many failed attempts)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity_at', models.DateTimeField(blank=True, help_text='Last time user was active on the platform', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='6-digit OTP code', max_length=6)),
                ('expires_at', models.DateTimeField(help_text='When this OTP expires')),
                ('used', models.BooleanField(default=False, help_text='Whether this OTP has been used')),
                ('used_at', models.DateTimeField(blank=True, help_text='When this OTP was used', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address that requested this OTP', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='Browser/device info', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='User this OTP belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OTP',
                'verbose_name_plural': 'OTPs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrustedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_token', models.CharField(help_text='Unique token stored in browser cookie', max_length=64, unique=True)),
                ('device_name', models.CharField(help_text="Friendly name like 'Chrome on Windows'", max_length=200)),
                ('device_type', models.CharField(blank=True, help_text='Device type (desktop, mobile, tablet)', max_length=100)),
                ('browser', models.CharField(blank=True, help_text='Browser name and version', max_length=100)),
                ('os', models.CharField(blank=True, help_text='Operating system', max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address when device was trusted', null=True)),
                ('location', models.CharField(blank=True, help_text='Geographic location (city, country)', max_length=200)),
                ('last_used_at', models.DateTimeField(auto_now=True, help_text='Last time this device was used')),
                ('expires_at', models.DateTimeField(help_text='When this trusted device expires (30 days)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this device is still trusted (can be revoked)')),
                ('user', models.ForeignKey(help_text='User who owns this device', on_delete=django.db.models.deletion.CASCADE, related_name='trusted_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trusted Device',
                'verbose_name_plural': 'Trusted Devices',
                'ordering': ['-last_used_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='account_use_email_553b8f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['kyc_status'], name='account_use_kyc_sta_de69f0_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email_verified'], name='account_use_email_v_f44b92_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['user', '-created_at'], name='account_otp_user_id_15318f_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['code', 'used'], name='account_otp_code_04ae8b_idx'),
        ),
        migrations.AddIndex(
            model_name='trusteddevice',
            index=models.Index(fields=['user', 'is_active'], name='account_tru_user_id_ddcee2_idx'),
        ),
        migrations.AddIndex(
            model_name='trusteddevice',
            index=models.Index(fields=['device_token'], name='account_tru_device__fb55b4_idx'),
        ),
    ]
