# Generated by Django 6.1.1 on 2026-09-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_token',
            field=models.CharField(blank=True, help_text='Token for password reset link', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
