# Generated by Django 6.1.1 on 2026-09-04 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_suspended_at_user_suspended_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('banned', 'Permanently Banned')], default='active', help_text="Current status of the user's account", max_length=20),
        ),
    ]
