# Generated by Django 6.1.1 on 2026-09-05 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Deposit amount in USD', max_digits=20)),
                ('payment_method', models.CharField(choices=[('btc', 'Bitcoin (BTC)'), ('eth', 'Ethereum (ETH)'), ('usdt', 'USDT (TRC20)'), ('bank_wire', 'Bank Wire Transfer')], help_text='Payment method used', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current status of the deposit', max_length=20)),
                ('transaction_reference', models.CharField(blank=True, help_text='Transaction hash or reference number from payment provider', max_length=200)),
                ('processed_at', models.DateTimeField(blank=True, help_text='When the deposit was processed', null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes from admin')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (shown to user)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.ForeignKey(blank=True, help_text='Admin who processed this deposit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_deposits', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User making the deposit', on_delete=django.db.models.deletion.CASCADE, related_name='deposit_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deposit Request',
                'verbose_name_plural': 'Deposit Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='transaction_user_id_cfdf14_idx'), models.Index(fields=['status'], name='transaction_status_9c1689_idx'), models.Index(fields=['-created_at'], name='transaction_created_ee5952_idx')],
            },
        ),
    ]
