# Generated by Django 6.1.1 on 2026-09-05 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Withdrawal amount in USD', max_digits=20)),
                ('payment_method', models.CharField(choices=[('btc', 'Bitcoin (BTC)'), ('eth', 'Ethereum (ETH)'), ('usdt', 'USDT (TRC20)'), ('bank_wire', 'Bank Wire Transfer'), ('sepa', 'SEPA Transfer')], help_text='Withdrawal method', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='pending', help_text='Current status of the withdrawal', max_length=20)),
                ('destination_address', models.CharField(help_text='Destination wallet address or bank account details', max_length=500)),
                ('destination_name', models.CharField(blank=True, help_text='Name on the destination account (for bank transfers)', max_length=200)),
                ('network', models.CharField(blank=True, help_text='Blockchain network (e.g., ERC20, TRC20, Bitcoin Mainnet)', max_length=50)),
                ('network_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Network/processing fee deducted from withdrawal', max_digits=20)),
                ('amount_after_fee', models.DecimalField(decimal_places=2, help_text='Amount user receives after fees', max_digits=20)),
                ('transaction_hash', models.CharField(blank=True, help_text='Blockchain transaction hash or bank reference', max_length=200)),
                ('processed_at', models.DateTimeField(blank=True, help_text='When the withdrawal was processed', null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes from admin')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (shown to user)')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address where withdrawal was requested', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='Browser/device info when requested', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.ForeignKey(blank=True, help_text='Admin who processed this withdrawal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User requesting the withdrawal', on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Withdrawal Request',
                'verbose_name_plural': 'Withdrawal Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='transaction_user_id_6450fc_idx'), models.Index(fields=['status'], name='transaction_status_6a9840_idx'), models.Index(fields=['-created_at'], name='transaction_created_7512ca_idx')],
            },
        ),
    ]
