# Generated by Django 6.1.1 on 2026-09-05 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_withdrawalrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('investment', 'Investment'), ('strategy_return', 'Strategy Return'), ('liquidation', 'Liquidation'), ('fee', 'Fee'), ('bonus', 'Bonus'), ('balance_adjustment', 'Balance Adjustment')], help_text='Type of transaction', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount', max_digits=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='completed', max_length=20)),
                ('reference', models.CharField(help_text='Unique transaction reference', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the transaction')),
                ('balance_before', models.DecimalField(decimal_places=2, help_text="User's balance before this transaction", max_digits=20)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text="User's balance after this transaction", max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('related_deposit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='transaction.depositrequest')),
                ('related_withdrawal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='transaction.withdrawalrequest')),
                ('user', models.ForeignKey(help_text='User this transaction belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='transaction_user_id_d29ed6_idx'), models.Index(fields=['transaction_type'], name='transaction_transac_33a64a_idx'), models.Index(fields=['status'], name='transaction_status_62e809_idx'), models.Index(fields=['reference'], name='transaction_referen_513dc0_idx')],
            },
        ),
    ]
