# Generated by Django 6.1.1 on 2026-09-05 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='depositrequest',
            name='created_by_admin',
            field=models.ForeignKey(blank=True, help_text='Admin who manually created this transaction (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manually_created_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='depositrequest',
            name='effective_date',
            field=models.DateTimeField(blank=True, help_text='Effective date of the transaction (for backdating). If blank, uses created_at.', null=True),
        ),
    ]
