# Generated by Django 6.1.1 on 2026-09-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_remove_depositrequest_created_by_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositrequest',
            name='payment_method',
            field=models.CharField(choices=[('bank_wire', 'Bank Wire Transfer'), ('sepa', 'SEPA Transfer'), ('check', "Cashier's Check")], help_text='Payment method used', max_length=20),
        ),
    ]
