# Generated by Django 6.1.1 on 2026-09-04 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(blank=True, max_length=200)),
                ('invested_coin', models.CharField(choices=[('btc', 'Bitcoin (BTC)'), ('eth', 'Ethereum (ETH)'), ('usdt', 'USDT'), ('usdc', 'USDC'), ('multi', 'Multi-Asset'), ('custom', 'Custom')], default='btc', max_length=20)),
                ('strategy_type', models.CharField(default='DCA', max_length=50)),
                ('current_price', models.DecimalField(decimal_places=2, default=100.0, max_digits=20)),
                ('initial_price', models.DecimalField(decimal_places=2, default=100.0, max_digits=20)),
                ('min_investment', models.DecimalField(decimal_places=2, default=100.0, max_digits=20)),
                ('management_fee', models.DecimalField(decimal_places=2, default=1.5, max_digits=5)),
                ('risk_level', models.CharField(choices=[('very_low', 'Very Low Risk'), ('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('very_high', 'Very High Risk')], default='medium', max_length=20)),
                ('ai_accuracy', models.DecimalField(decimal_places=2, default=94.7, max_digits=5)),
                ('min_holding_period', models.IntegerField(default=6)),
                ('total_investors', models.IntegerField(default=0)),
                ('total_invested', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('market_cap', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('closed', 'Closed')], default='active', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_strategies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Strategy',
                'verbose_name_plural': 'Strategies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpinRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('spin_up', 'Spin Up'), ('spin_down', 'Spin Down'), ('manual_set', 'Manual Set'), ('initial', 'Initial Price')], max_length=20)),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('amount_changed', models.DecimalField(decimal_places=2, max_digits=20)),
                ('reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spin_records', to=settings.AUTH_USER_MODEL)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spins', to='coin.strategy')),
            ],
            options={
                'verbose_name': 'Spin Record',
                'verbose_name_plural': 'Spin Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StrategyInvestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invested_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('shares', models.DecimalField(decimal_places=8, max_digits=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('liquidated', 'Liquidated')], default='active', max_length=20)),
                ('invested_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('liquidated_at', models.DateTimeField(blank=True, null=True)),
                ('total_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investors', to='coin.strategy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_investments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Strategy Investor',
                'verbose_name_plural': 'Strategy Investors',
                'ordering': ['-invested_at'],
            },
        ),
        migrations.CreateModel(
            name='StrategyPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('trades_count', models.IntegerField(default=0)),
                ('daily_change', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('daily_change_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to='coin.strategy')),
            ],
            options={
                'verbose_name': 'Strategy Performance',
                'verbose_name_plural': 'Strategy Performance Records',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='strategy',
            index=models.Index(fields=['status', 'is_public'], name='coin_strate_status_ab2ecc_idx'),
        ),
        migrations.AddIndex(
            model_name='strategy',
            index=models.Index(fields=['risk_level'], name='coin_strate_risk_le_f97495_idx'),
        ),
        migrations.AddIndex(
            model_name='strategy',
            index=models.Index(fields=['-current_price'], name='coin_strate_current_77f890_idx'),
        ),
        migrations.AddIndex(
            model_name='spinrecord',
            index=models.Index(fields=['strategy', '-created_at'], name='coin_spinre_strateg_9a03e8_idx'),
        ),
        migrations.AddIndex(
            model_name='spinrecord',
            index=models.Index(fields=['action'], name='coin_spinre_action_5f945f_idx'),
        ),
        migrations.AddIndex(
            model_name='spinrecord',
            index=models.Index(fields=['-created_at'], name='coin_spinre_created_ed20d7_idx'),
        ),
        migrations.AddIndex(
            model_name='strategyinvestor',
            index=models.Index(fields=['strategy', 'status'], name='coin_strate_strateg_da088d_idx'),
        ),
        migrations.AddIndex(
            model_name='strategyinvestor',
            index=models.Index(fields=['user', 'status'], name='coin_strate_user_id_0dc476_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='strategyinvestor',
            unique_together={('strategy', 'user')},
        ),
        migrations.AddIndex(
            model_name='strategyperformance',
            index=models.Index(fields=['strategy', '-date'], name='coin_strate_strateg_a9ed64_idx'),
        ),
        migrations.AddIndex(
            model_name='strategyperformance',
            index=models.Index(fields=['-date'], name='coin_strate_date_99c2e9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='strategyperformance',
            unique_together={('strategy', 'date')},
        ),
    ]
