# Generated by Django 6.1.1 on 2026-09-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('closed', 'Closed'), ('deleted', 'Deleted')], default='active', max_length=20),
        ),
    ]
