# Generated by Django 6.1.1 on 2026-09-05 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
                ('residential_address', models.TextField()),
                ('document_type', models.CharField(choices=[('passport', 'Passport'), ('national_id', 'National ID Card'), ('drivers_license', "Driver's License")], help_text='Type of ID document submitted', max_length=20)),
                ('document_number', models.CharField(help_text='ID/Passport number', max_length=100)),
                ('document_expiry', models.DateField(blank=True, help_text='Document expiry date', null=True)),
                ('document_front', models.ImageField(help_text='Front side of ID document', upload_to='kyc/documents/%Y/%m/%d/')),
                ('document_back', models.ImageField(blank=True, help_text='Back side of ID document (if applicable)', null=True, upload_to='kyc/documents/%Y/%m/%d/')),
                ('selfie', models.ImageField(help_text='Selfie photo for identity verification', upload_to='kyc/selfies/%Y/%m/%d/')),
                ('proof_of_address', models.FileField(blank=True, help_text='Proof of address (utility bill, bank statement)', null=True, upload_to='kyc/address/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resubmission_requested', 'Resubmission Requested')], default='pending', max_length=25)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (shown to user)')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes from reviewer')),
                ('submission_number', models.IntegerField(default=1)),
                ('resubmission_count', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed this submission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_kyc', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User who submitted KYC', on_delete=django.db.models.deletion.CASCADE, related_name='kyc_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KYC Submission',
                'verbose_name_plural': 'KYC Submissions',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['user', '-submitted_at'], name='kyc_kycsubm_user_id_59f7b0_idx'), models.Index(fields=['status'], name='kyc_kycsubm_status_1d4f35_idx')],
            },
        ),
    ]
