# Generated by Django 6.1.1 on 2026-09-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycsubmission',
            name='address_doc_type',
            field=models.CharField(blank=True, help_text='Type of address proof document (e.g., utility_bill, bank_statement)', max_length=50),
        ),
    ]
