# Generated by Django 6.1.1 on 2026-09-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_kycsubmission_address_doc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycsubmission',
            name='address_needs_resubmit',
            field=models.BooleanField(default=False, help_text='True if admin requested address proof resubmission'),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='id_needs_resubmit',
            field=models.BooleanField(default=False, help_text='True if admin requested ID document resubmission'),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='selfie_needs_resubmit',
            field=models.BooleanField(default=False, help_text='True if admin requested selfie resubmission'),
        ),
    ]
